[tool.poetry]
name = "acropolis-visualisation"
version = "0.1.0"
description = "A package to visualise ACROPLIS network data"
authors = ["patrickaigner <patrick.aigner@tum.de>"]
readme = "README.md"
packages = [{include = "acropolis_visualisation"}]

[tool.poetry.dependencies]
python = "^3.11"
polars = "^0.18.6"
pendulum = "^2.1.2"
asyncpg = "^0.28.0"
seaborn = "^0.12.2"
numpy = "^1.25.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
